# Generated by Django 2.2.16 on 2022-09-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20220915_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Картинка', upload_to='posts/', verbose_name='Картинка'),
        ),
    ]
